### ISSUE TITLE
Mac Installation

### ISSUE THREAD

**Issue by j23414** [arendsee/synder#1]
I'm working on a iMac (21.5-inch, Late 2015) OS X El Capitan. Having some trouble with installation. I can fetch the code fine but compiling is giving some errors...

```
git clone https://github.com/arendsee/synder.git
cd synder
make
```

and I get...

```
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -c -Wall -g -O2 test.[ch]
In file included from test.c:7:
./itree/search.h:49:1: error: unknown type name 'uint'; did you mean 'int'?
uint count_point_overlaps(uint pnt, IntervalTree * tree);
^~~~
int
./itree/search.h:49:27: error: unknown type name 'uint'; did you mean 'int'?
uint count_point_overlaps(uint pnt, IntervalTree * tree);
                          ^~~~
                          int
./itree/search.h:57:1: error: unknown type name 'uint'; did you mean 'int'?
uint count_interval_overlaps(Interval * interval, IntervalTree * tree);
^~~~
int
./itree/search.h:72:43: error: unexpected type name 'IntervalTree': expected identifier
IntervalResult * get_point_overlaps(uint, IntervalTree *);
                                          ^
./itree/search.h:72:56: error: expected ')'
IntervalResult * get_point_overlaps(uint, IntervalTree *);
                                                       ^
./itree/search.h:72:36: note: to match this '('
IntervalResult * get_point_overlaps(uint, IntervalTree *);
                                   ^
./itree/search.h:72:37: error: a parameter list without types is only allowed in a function definition
IntervalResult * get_point_overlaps(uint, IntervalTree *);
                                    ^
6 errors generated.
make[1]: *** [test.o] Error 1
make: *** [all] Error 2
```

My gcc version is 

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by arendsee** [comment]
Thanks for pointing that out.

Try the newest commit to the dev branch (866fa0). There were some mistakes in the headers. If this works for you, I'll push it to master.

I haven't tested this of OSX yet, but I am pretty sure the shell script `make-synder-db.sh` will break (OSX sed versus GNU sed issues). Tell me how that goes for you.

Hope this helps!

**Comment by j23414** [comment]
Just tried the dev branch (I think I fetched it correctly)...the c code is still not compiling. I might try one file at a time, maybe starting wherever `uint` is defined. Thanks for the header fixes! I see those. Is util/make-synder-db.sh preparing synder input, running synder or creating new makefiles?

```
$ git clone -b dev https://github.com/arendsee/synder.git synder-dev
$ cd synder-dev/
$ make
```

results in the following output with errors...some of the files compiled, but it got stuck at interval

```
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -c -Wall -g -O2 main.c
gcc -c -Wall -g -O2 test.[ch]
gcc -c -Wall -g -O2 io.[ch]
gcc -c -Wall -g -O2 genome.[ch]
gcc -c -Wall -g -O2 analysis.[ch]
gcc -c -Wall -g -O2 contig.[ch]
gcc -c -Wall -g -O2 itree/interval.[ch]
itree/interval.c:6:26: error: unknown type name 'uint'; did you mean 'int'?
Interval * init_interval(uint start, uint stop){
                         ^~~~
                         int
itree/interval.c:6:38: error: unknown type name 'uint'; did you mean 'int'?
Interval * init_interval(uint start, uint stop){
                                     ^~~~
                                     int
itree/interval.c:6:12: error: conflicting types for 'init_interval'
Interval * init_interval(uint start, uint stop){
           ^
itree/interval.h:12:12: note: previous declaration is here
Interval * init_interval(unsigned int start, unsigned int stop);
           ^
3 errors generated.
make[1]: *** [interval.o] Error 1
make: *** [all] Error 2
```

Actually a global.h and global.c  is nice for global datatype renaming. Right now maybe interval.h needs to import itree.h?

**Comment by mhhur** [comment]
uint is unsigned int. So you can replace from "uint" to "unsigned int".

**Comment by j23414** [comment]
Replacing `uint` with `unsigned int` in the interval.c file results in successful compilation on Mac. Thanks : )

**Comment by arendsee** [comment]
Try pulling master now and compile that.

**Comment by j23414** [comment]
Pulled the master. Other than a warning message, it compiles perfectly! Thanks :) 

```
$ make
cd src && /Applications/Xcode.app/Contents/Developer/usr/bin/make
gcc -c -Wall -g -O2 main.c
gcc -c -Wall -g -O2 test.[ch]
gcc -c -Wall -g -O2 io.[ch]
gcc -c -Wall -g -O2 genome.[ch]
gcc -c -Wall -g -O2 analysis.[ch]
gcc -c -Wall -g -O2 contig.[ch]
gcc -c -Wall -g -O2 itree/interval.[ch]
gcc -c -Wall -g -O2 itree/itree.[ch]
gcc -c -Wall -g -O2 itree/search.[ch]
itree/search.c:150:15: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
        while(!IS_ROOT && IS_CIS){ ASCEND }
              ^~~~~~~~
itree/search.c:150:15: note: add parentheses after the '!' to evaluate the comparison first
        while(!IS_ROOT && IS_CIS){ ASCEND }
              ^
               (      )
itree/search.c:150:15: note: add parentheses around left hand side expression to silence this warning
1 warning generated.
gcc -c -Wall -g -O2 itree/ia.[ch]
gcc -c -Wall -g -O2 itree/iv.[ch]
gcc -c -Wall -g -O2 block.[ch]
gcc -c -Wall -g -O2 synmap.[ch]
gcc -c -Wall -g -O2 ui.[ch]
gcc -c -Wall -g -O2 contiguous.[ch]
gcc -c -Wall -g -O2 lev.[ch]
gcc -o synder -Wall -g -O2 main.o test.o io.o genome.o analysis.o contig.o interval.o itree.o search.o ia.o iv.o block.o synmap.o ui.o contiguous.o lev.o
mv src/synder synder
```

**Comment by arendsee** [comment]
Great! I'll close the issue.
